package feeds

type FeedConfig struct {
	URL             string
	Source          string
	Header          string
	Topic           string
	Agent           string // // "bot", "chrome", "reader"
	EnhancedHeaders bool   // When true, use enhanced headers for the request
}

var Feeds = []FeedConfig{
	// {
	// 	URL:             "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
	// 	Source:          "nyt-world",
	// 	Header:          "nyt",
	// 	Topic:           "geopolitics",
	// 	Agent:           "bot",
	// 	EnhancedHeaders: false,
	// },
	// {
	// 	URL:             "https://www.reddit.com/r/EarningsWhisper/.rss",
	// 	Source:          "reddit-earningswhisper",
	// 	Header:          "r/earningswhisper",
	// 	Topic:           "finance",
	// 	Agent:           "bot",
	// 	EnhancedHeaders: false,
	// },
	// {
	// 	URL:             "https://feeds.content.dowjones.io/public/rss/mw_bulletins",
	// 	Source:          "marketwatch",
	// 	Header:          "",
	// 	Topic:           "finance",
	// 	Description:     true,
	// 	Agent:           "bot",
	// 	EnhancedHeaders: false,
	// },
	{
		URL:             "https://hnrss.org/frontpage",
		Source:          "hacker-news",
		Header:          "hackernews",
		Topic:           "technology",
		Agent:           "bot",
		EnhancedHeaders: false,
	},
	{
		URL:             "https://rss.slashdot.org/Slashdot/slashdotMain",
		Source:          "slashdot",
		Header:          "slashdot",
		Topic:           "technology",
		Agent:           "bot",
		EnhancedHeaders: false,
	},
	{
		URL:             "https://techmeme.com/feed.xml",
		Source:          "techmeme",
		Header:          "techmeme",
		Topic:           "technology",
		Agent:           "bot",
		EnhancedHeaders: false,
	},
	{
		URL:             "https://semianalysis.com/feed/",
		Source:          "semi-analysis",
		Header:          "semianalysis",
		Topic:           "technology",
		Agent:           "bot",
		EnhancedHeaders: false,
	},
	{
		URL:             "https://github.com/drogonframework/drogon/releases.atom",
		Source:          "github-drogon",
		Header:          "drogonframework/drogon",
		Topic:           "technology",
		Agent:           "bot",
		EnhancedHeaders: false,
	},
	{
		URL:             "https://www.reddit.com/r/hardware/.rss",
		Source:          "reddit-hardware",
		Header:          "r/hardware",
		Topic:           "technology",
		Agent:           "bot",
		EnhancedHeaders: false,
	},
	{
		URL:             "https://www.reddit.com/r/cpp/.rss",
		Source:          "reddit-cpp",
		Header:          "r/cpp",
		Topic:           "technology",
		Agent:           "bot",
		EnhancedHeaders: false,
	},
	{
		URL:             "https://www.reddit.com/r/cpp_questions/.rss",
		Source:          "reddit-cppquestions",
		Header:          "r/cppquestions",
		Topic:           "technology",
		Agent:           "bot",
		EnhancedHeaders: false,
	},
	{
		URL:             "https://www.reddit.com/r/NixOS/.rss",
		Source:          "reddit-nixos",
		Header:          "r/nixos",
		Topic:           "technology",
		Agent:           "bot",
		EnhancedHeaders: false,
	},
	// {
	// 	URL:             "https://techcrunch.com/feed/",
	// 	Source:          "techcrunch",
	// 	Header:          "techcrunch",
	// 	Topic:           "technology",
	// 	Agent:           "bot",
	// 	EnhancedHeaders: false,
	// },
	// {
	// 	URL:             "https://feeds.feedburner.com/TheHackersNews",
	// 	Source:          "the-hackers-news",
	// 	Header:          "thehackernews",
	// 	Topic:           "technology",
	// 	Agent:           "bot",
	// 	EnhancedHeaders: false,
	// },
	// {
	// 	URL:             "https://rss.nytimes.com/services/xml/rss/nyt/Business.xml",
	// 	Source:          "nyt-business",
	// 	Header:          "",
	// 	Topic:           "finance",
	// 	Description:     true,
	// 	Agent:           "bot",
	// 	EnhancedHeaders: false,
	// },
	// {
	// 	URL:             "https://www.reddit.com/r/finance/.rss",
	// 	Source:          "reddit-finance",
	// 	Header:          "r/finance",
	// 	Topic:           "finance",
	// 	Description:     true,
	// 	Agent:           "bot",
	// 	EnhancedHeaders: false,
	// },
	// {
	// 	URL:             "https://boeing.mediaroom.com/news-releases-statements?pagetemplate=rss&category=794",
	// 	Source:          "boeing",
	// 	Header:          "",
	// 	Topic:           "geopolitics",
	// 	Description:     true,
	// 	Agent:           "bot",
	// 	EnhancedHeaders: false,
	// },
	// {
	// 	URL:             "https://investorrelations.gd.com/rss/pressrelease.aspx",
	// 	Source:          "gd",
	// 	Header:          "",
	// 	Topic:           "geopolitics",
	// 	Description:     true,
	// 	Agent:           "bot",
	// 	EnhancedHeaders: false,
	// },
	// {
	// 	URL:             "https://www.l3harris.com/feeds/newsroom/rss.xml",
	// 	Source:          "l3harris",
	// 	Header:          "",
	// 	Topic:           "geopolitics",
	// 	Description:     true,
	// 	Agent:           "bot",
	// 	EnhancedHeaders: false,
	// },
	// {
	// 	URL:             "https://www.rtx.com/rss-feeds/news",
	// 	Source:          "raytheon",
	// 	Header:          "",
	// 	Topic:           "geopolitics",
	// 	Description:     true,
	// 	Agent:           "chrome",
	// 	EnhancedHeaders: false,
	// },
	// {
	// 	URL:             "https://news.lockheedmartin.com/news-releases?pagetemplate=rss",
	// 	Source:          "lockheedmartin",
	// 	Header:          "",
	// 	Topic:           "geopolitics",
	// 	Description:     true,
	// 	Agent:           "bot",
	// 	EnhancedHeaders: false,
	// },
	// {
	// 	URL:             "https://www.reddit.com/r/wallstreetbets/.rss",
	// 	Source:          "reddit-wallstreetbets",
	// 	Header:          "r/wallstreetbets",
	// 	Topic:           "finance",
	// 	Description:     true,
	// 	Agent:           "bot",
	// 	EnhancedHeaders: false,
	// },
	// {
	// 	URL:             "https://www.reddit.com/r/Intelligence/.rss",
	// 	Source:          "reddit-intelligence",
	// 	Header:          "r/Intelligence",
	// 	Topic:           "geopolitics",
	// 	Description:     true,
	// 	Agent:           "bot",
	// 	EnhancedHeaders: false,
	// },
	// {
	// 	URL:             "https://www.nato.int/cps/rss/en/natohq/rssFeed.xsl/rssFeed.xml",
	// 	Source:          "nato",
	// 	Header:          "NATO",
	// 	Topic:           "geopolitics",
	// 	Description:     true,
	// 	Agent:           "bot",
	// 	EnhancedHeaders: false,
	// },
	// {
	// 	URL:             "https://www.state.gov/rss-feed/press-releases/feed/",
	// 	Source:          "us-state-dept",
	// 	Header:          "State Dept.",
	// 	Topic:           "geopolitics",
	// 	Description:     false,
	// 	Agent:           "chrome",
	// 	EnhancedHeaders: false,
	// },
	// {
	// 	URL:             "https://www.reddit.com/r/ValueInvesting/.rss",
	// 	Source:          "reddit-valueinvesting",
	// 	Header:          "r/ValueInvesting",
	// 	Topic:           "finance",
	// 	Description:     true,
	// 	Agent:           "bot",
	// 	EnhancedHeaders: false,
	// },
	// {
	// 	URL:             "https://www.rusi.org/rss/whats-new.xml",
	// 	Source:          "rusi",
	// 	Header:          "rusi",
	// 	Topic:           "geopolitics",
	// 	Agent:           "bot",
	// 	EnhancedHeaders: false,
	// },
	// {
	// 	URL:             "https://www.reddit.com/r/Economics/.rss",
	// 	Source:          "reddit-economics",
	// 	Header:          "r/Economics",
	// 	Topic:           "finance",
	// 	Description:     true,
	// 	Agent:           "bot",
	// 	EnhancedHeaders: false,
	// },
	// {
	// 	URL:             "https://feeds.content.dowjones.io/public/rss/RSSMarketsMain",
	// 	Source:          "wsj",
	// 	Header:          "",
	// 	Topic:           "finance",
	// 	Description:     true,
	// 	Agent:           "bot",
	// 	EnhancedHeaders: false,
	// },
	// {
	// 	URL:             "https://www.reddit.com/r/CredibleDefense/.rss",
	// 	Source:          "reddit-credible_defense",
	// 	Header:          "r/CredibleDefense",
	// 	Topic:           "geopolitics",
	// 	Description:     true,
	// 	Agent:           "bot",
	// 	EnhancedHeaders: false,
	// },
	// {
	// 	URL:             "https://ec.europa.eu/eurostat/en/search?p_p_id=estatsearchportlet_WAR_estatsearchportlet&p_p_lifecycle=2&p_p_state=maximized&p_p_mode=view&p_p_resource_id=atom&_estatsearchportlet_WAR_estatsearchportlet_collection=CAT_PREREL",
	// 	Source:          "eurostat",
	// 	Header:          "eurostat",
	// 	Topic:           "finance",
	// 	Agent:           "bot",
	// 	EnhancedHeaders: false,
	// },

	// {
	// 	URL:             "https://www.reddit.com/r/StockMarket/.rss",
	// 	Source:          "reddit-stockmarket",
	// 	Header:          "r/StockMarket",
	// 	Topic:           "finance",
	// 	Description:     true,
	// 	Agent:           "bot",
	// 	EnhancedHeaders: false,
	// },
	// {
	// 	URL:             "https://www.reddit.com/r/stocks/.rss",
	// 	Source:          "reddit-stocks",
	// 	Header:          "r/stocks",
	// 	Topic:           "finance",
	// 	Description:     true,
	// 	Agent:           "bot",
	// 	EnhancedHeaders: false,
	// },
	// {
	// 	URL:             "https://www.reddit.com/r/evolution/.rss",
	// 	Source:          "reddit-evolution",
	// 	Header:          "r/evolution",
	// 	Topic:           "technology",
	// 	Description:     true,
	// 	Agent:           "bot",
	// 	EnhancedHeaders: false,
	// },
	{
		URL:             "https://www.reddit.com/r/worldnews/.rss",
		Source:          "reddit-worldnews",
		Header:          "r/worldnews",
		Topic:           "geopolitics",
		Agent:           "bot",
		EnhancedHeaders: false,
	},
	{
		URL:             "https://www.reddit.com/r/geopolitics/.rss",
		Source:          "reddit-geopolitics",
		Header:          "r/geopolitics",
		Topic:           "geopolitics",
		Agent:           "bot",
		EnhancedHeaders: false,
	},
	{
		URL:             "https://www.reddit.com/r/anime_titties/.rss",
		Source:          "reddit-anime_titties",
		Header:          "r/anime_titties",
		Topic:           "geopolitics",
		Agent:           "bot",
		EnhancedHeaders: false,
	},
	{
		URL:             "https://www.darpa.mil/rss.xml",
		Source:          "darpa",
		Header:          "darpa",
		Topic:           "geopolitics",
		Agent:           "bot",
		EnhancedHeaders: false,
	},
	{
		URL:             "https://www.foreignaffairs.com/rss.xml",
		Source:          "foreign-affairs",
		Header:          "foreignaffairs",
		Topic:           "geopolitics",
		Agent:           "bot",
		EnhancedHeaders: false,
	},
	{
		URL:             "https://www.rand.org/topics/international-affairs.html",
		Source:          "rand-international-affairs",
		Header:          "rand",
		Topic:           "geopolitics",
		Agent:           "chrome",
		EnhancedHeaders: false,
	},
	{
		URL:             "https://www.understandingwar.org/feeds.xml",
		Source:          "isw",
		Header:          "isw",
		Topic:           "geopolitics",
		Agent:           "bot",
		EnhancedHeaders: false,
	},
	{
		URL:             "https://www.israelhayom.com/feed/",
		Source:          "israel-hayom",
		Header:          "hayom",
		Topic:           "geopolitics",
		Agent:           "bot",
		EnhancedHeaders: false,
	},
	{
		URL:             "https://www.jpost.com/rss/rssfeedsfrontpage.aspx",
		Source:          "jpost",
		Header:          "jpost",
		Topic:           "geopolitics",
		Agent:           "bot",
		EnhancedHeaders: false,
	},
	{
		URL:             "https://www.timesofisrael.com/feed/",
		Source:          "times-of-israel",
		Header:          "timesofisrael",
		Topic:           "geopolitics",
		Agent:           "bot",
		EnhancedHeaders: false,
	},
	{
		URL:             "https://www.haaretz.com/srv/haaretz-latest-headlines",
		Source:          "haaretz",
		Header:          "haaretz",
		Topic:           "geopolitics",
		Agent:           "bot",
		EnhancedHeaders: false,
	},
	{
		URL:             "https://www.cgtn.com/subscribe/rss/section/politics.xml",
		Source:          "cgtn",
		Header:          "cgtn",
		Topic:           "geopolitics",
		Agent:           "bot",
		EnhancedHeaders: false,
	},
	{
		URL:             "https://www.scmp.com/rss/318199/feed/",
		Source:          "scmp",
		Header:          "scmp",
		Topic:           "geopolitics",
		Agent:           "bot",
		EnhancedHeaders: false,
	},
	{
		URL:             "https://valdaiclub.com/export/rss/feed.xml",
		Source:          "valdai",
		Header:          "valdai",
		Topic:           "geopolitics",
		Agent:           "bot",
		EnhancedHeaders: false,
	},
	{
		URL:             "https://russiancouncil.ru/en/rss/analytics-and-comments/",
		Source:          "riac",
		Header:          "russiancouncil",
		Topic:           "geopolitics",
		Agent:           "bot",
		EnhancedHeaders: false,
	},
	// {
	// 	URL:             "https://warontherocks.com/feed/",
	// 	Source:          "warontherocks",
	// 	Header:          "warontherocks",
	// 	Topic:           "geopolitics",
	// 	Agent:           "bot",
	// 	EnhancedHeaders: false,
	// },
	// {
	// 	URL:             "https://www.atlanticcouncil.org/feed/",
	// 	Source:          "atlantic-council",
	// 	Header:          "atlanticcouncil",
	// 	Topic:           "geopolitics",
	// 	Agent:           "bot",
	// 	EnhancedHeaders: false,
	// },
	// {
	// 	URL:             "https://www.chathamhouse.org/path/whatsnew.xml",
	// 	Source:          "chatham-house",
	// 	Header:          "chathamhouse",
	// 	Topic:           "geopolitics",
	// 	Agent:           "bot",
	// 	EnhancedHeaders: false,
	// },
	// {
	// 	URL:             "https://investor.oracle.com/rss/pressrelease.aspx",
	// 	Source:          "oracle-press",
	// 	Header:          "oracle",
	// 	Topic:           "technology",
	// 	Agent:           "bot",
	// 	EnhancedHeaders: false,
	// },
	// {
	// 	URL:             "https://blogs.oracle.com/connect/rss",
	// 	Source:          "oracle-blogs",
	// 	Header:          "oracle",
	// 	Topic:           "technology",
	// 	Agent:           "chrome",
	// 	EnhancedHeaders: true,
	// },
	// {
	// 	URL:             "https://www.reddit.com/r/Israel/.rss",
	// 	Source:          "reddit-israel",
	// 	Header:          "r/Israel",
	// 	Topic:           "geopolitics",
	// 	Description:     true,
	// 	Agent:           "bot",
	// 	EnhancedHeaders: false,
	// },
	// {
	// 	URL:             "https://www.reddit.com/r/MilitaryPorn/.rss",
	// 	Source:          "reddit-militaryporn",
	// 	Header:          "r/MilitaryPorn",
	// 	Topic:           "geopolitics",
	// 	Description:     true,
	// 	Agent:           "bot",
	// 	EnhancedHeaders: false,
	// },

	// {
	// 	URL:             "https://breakingdefense.com/full-rss-feed/?v=2",
	// 	Source:          "breaking-defense",
	// 	Header:          "",
	// 	Topic:           "geopolitics",
	// 	Description:     false,
	// 	Agent:           "bot",
	// 	EnhancedHeaders: false,
	// },
	// {
	// 	URL:             "https://www.defensenews.com/arc/outboundfeeds/rss/?outputType=xml",
	// 	Source:          "defense-news",
	// 	Header:          "",
	// 	Topic:           "geopolitics",
	// 	Description:     false,
	// 	Agent:           "bot",
	// 	EnhancedHeaders: false,
	// },
	{
		URL:             "https://www.federalreserve.gov/feeds/press_monetary.xml",
		Source:          "fed",
		Header:          "fed",
		Topic:           "finance",
		Agent:           "bot",
		EnhancedHeaders: false,
	},
	{
		URL:             "https://www.ecb.europa.eu/rss/press.html",
		Source:          "ecb",
		Header:          "ecb",
		Topic:           "finance",
		Agent:           "bot",
		EnhancedHeaders: false,
	},
	// {
	// 	URL:             "https://www.ft.com/rss/home",
	// 	Source:          "ft",
	// 	Header:          "ft",
	// 	Topic:           "finance",
	// 	Agent:           "bot",
	// 	EnhancedHeaders: false,
	// },
	// {
	// 	URL:             "https://www.ft.com/markets?format=rss",
	// 	Source:          "ft-markets",
	// 	Header:          "ft",
	// 	Topic:           "finance",
	// 	Agent:           "bot",
	// 	EnhancedHeaders: false,
	// },
	{
		URL:             "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=100727362",
		Source:          "cnbc-world",
		Header:          "cnbc",
		Topic:           "finance",
		Agent:           "bot",
		EnhancedHeaders: false,
	},
	{
		URL:             "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=10000664",
		Source:          "cnbc-finance",
		Header:          "cnbc",
		Topic:           "finance",
		Agent:           "bot",
		EnhancedHeaders: false,
	},
	// {
	// 	URL:             "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=15838381",
	// 	Source:          "cnbc-squawk-street",
	// 	Header:          "cnbc",
	// 	Topic:           "finance",
	// 	Agent:           "bot",
	// 	EnhancedHeaders: false,
	// },
	// {
	// 	URL:             "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=15838368",
	// 	Source:          "cnbc-squawk-box",
	// 	Header:          "cnbc",
	// 	Topic:           "finance",
	// 	Agent:           "bot",
	// 	EnhancedHeaders: false,
	// },
	{
		URL:             "https://seekingalpha.com/market_currents.xml",
		Source:          "seekingalpha-currents",
		Header:          "seekingalphabreaking",
		Topic:           "finance",
		Agent:           "bot",
		EnhancedHeaders: false,
	},
	{
		URL:             "https://seekingalpha.com/feed.xml",
		Source:          "seekingalpha",
		Header:          "seekingalphaarticles",
		Topic:           "finance",
		Agent:           "bot",
		EnhancedHeaders: false,
	},
}
